## Linear Algrebra and Calculus (NumPy, SciPy, and SymPy)

Linear algebra and calculus are fundamental areas of mathematics that are widely used in various fields such as physics, engineering, computer science, and data science. In Python, libraries like NumPy, SciPy, and SymPy provide powerful tools for performing linear algebra and calculus operations efficiently.

### 1. NumPy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

### Creating Basic Arrays

`np.array()` is used to create arrays in NumPy. You can create 1D, 2D, and even higher-dimensional arrays.

In [238]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [239]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


`np.matrix()` is used to create matrices in NumPy. It is a specialized 2D array that provides additional functionality for linear algebra operations.

In [240]:
m = np.matrix("1 2 3; 4 5 6")
print(m)

n = np.matrix("1 2 3 4 5;"
              "6 7 8 9 10;"
              "11 12 13 14 15")
print(n)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


`arr.reshape()` is used to change the shape of an existing array without changing its data.

In [241]:
arr = np.array([1,2,3,4,5,6])

matrix = arr.reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


`arr.flatten()` is used to convert a multi-dimensional array into a 1D array.

In [242]:
flat = matrix.flatten()
print(flat)

[1 2 3 4 5 6]


Creating random arrays is also possible using functions like `np.random.rand()`, `np.random.randn()`, and `np.random.randint()`.

In [243]:
np.random.rand(3)

array([0.39256777, 0.41904228, 0.00515592])

In [ ]:
np.random.randint(1, 12, (3, 4))

array([[ 8,  8, 10,  9],
       [ 2,  1,  3,  9],
       [ 8,  3,  9,  4]])

###  Indexing and Slicing

Indexing and slicing in NumPy allows you to access and manipulate specific elements or subarrays within an array. You can use integer indexing, boolean indexing, and slicing techniques to extract data efficiently.

In [244]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])
print(arr[1:4])
print(arr[2:])
print(arr[:3])
print(arr[::2])

20
[20 30 40]
[30 40 50]
[10 20 30]
[10 30 50]


In [245]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# Row index 0
print(matrix[0])
# Element at row index 1, column index 2
print(matrix[1, 2])
# Entire rows
print(matrix[1, :])
# Entire columns
print(matrix[:, 1])

[1 2 3]
6
[4 5 6]
[2 5 8]


### Common Types of Matrices

Square Matrix is a matrix with the same number of rows and columns. It is often used in linear algebra for various operations.

In [246]:
square = np.array([[1,2], [3,4]])
print(square)

[[1 2]
 [3 4]]


Diagonal Matrix is a square matrix where all the elements outside the main diagonal are zero.

In [247]:
diag = np.diag([1,2,3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


Identity Matrix is a square matrix with ones on the main diagonal and zeros elsewhere. It serves as the multiplicative identity in matrix multiplication.

In [248]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Triangular Matrix is a square matrix where all the elements above or below the main diagonal are zero. It can be either upper triangular or lower triangular.

In [249]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(np.triu(A))
print(np.tril(A))

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


Transpose of a matrix is obtained by flipping the matrix over its diagonal, which means converting its rows into columns and vice versa. In NumPy, you can use the `.T` attribute to get the transpose of a matrix.

In [250]:
A = np.array([[1,2,3],
              [4,5,6]])

print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]


### Common Operations on Matrices

Common operations on matrices include addition, subtraction, multiplication, and division. In NumPy, you can use the `+`, `-`, `*`, and `/` operators for element-wise operations.

Note that multiplication of matrices has specific types such as element-wise multiplication and matrix multiplication. 

- Element-wise multiplication multiplies corresponding elements of two matrices. This is done using the `*` or `np.multiply()` operator in Python.

- Matrix multiplication (known as dot product) follows the rules of linear algebra. This is done using the `np.dot()` function or the `@` operator in Python.

- Outer product is a type of multiplication that results in a matrix from two vectors. The method `np.outer()` is used to compute the outer product of two vectors.

In [251]:
A = np.array([1,2,3])
B = np.array([4,5,6])

In [252]:
print(A + B)
print(np.add(A, B))

[5 7 9]
[5 7 9]


In [253]:
print(A - B)
print(np.subtract(A, B))

[-3 -3 -3]
[-3 -3 -3]


In [254]:
print(A / B)
print(np.divide(A, B))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [255]:
print(A * B)
print(np.multiply(A, B))

[ 4 10 18]
[ 4 10 18]


In [256]:
print(A * 10)
print(np.multiply(A, 10))

[10 20 30]
[10 20 30]


In [257]:
print(np.dot(A, B))

32


In [258]:
print(np.outer(A, B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### Mathematical Operations

Some common mathematical operations in NumPy include:

- `np.sum()`: Computes the sum of array elements along a specified axis.

- `np.mean()` and `np.median()`: Calculate the mean and median of array elements.

- `np.min()` and `np.max()`: Find the minimum and maximum values in an array.

- `np.std()` and `np.var()`: Compute the standard deviation and variance of array elements.

- `np.sqrt()` and `np.abs()`: Calculate the square root and absolute values of array elements.

- `np.power()` and `np.exp()`: Compute the power of array elements and the exponential function, respectively.

- `np.log()`, `np.log2()`, and `np.log10()`: Calculate the natural logarithm, base-2 logarithm, and base-10 logarithm of array elements.

In [259]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [260]:
data = np.array([10, 20, 30, 40, 50])

print(np.sum(data))
print(np.mean(data))
print(np.median(data))

150
30.0
30.0


In [261]:
print(np.min(data))
print(np.max(data))

10
50


In [262]:
print(np.var(data))
print(np.std(data))

200.0
14.142135623730951


In [263]:
print(np.sqrt(16))
print(np.abs(-25))

4.0
25


In [264]:
print(np.power(2, 5))
print(np.exp(1))

32
2.718281828459045


In [265]:
print(np.log(10))
print(np.log2(8))
print(np.log10(100))

2.302585092994046
3.0
2.0


### Linear Algebra

Determinant of a matrix can be calculated using `np.linalg.det()`. It is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the linear transformation described by the matrix.

In [266]:
A = np.array([[1, 2, 3],
              [3, 4, 3],
              [6, 6, 7]])
print(np.linalg.det(A))

-14.000000000000004


The inverse of a matrix can be computed using `np.linalg.inv()`. It is a matrix that, when multiplied with the original matrix, yields the identity matrix.

In [267]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.71428571 -0.28571429  0.42857143]
 [ 0.21428571  0.78571429 -0.42857143]
 [ 0.42857143 -0.42857143  0.14285714]]


System of linear equations can be solved using `np.linalg.solve()`. It finds the solution to a system of linear equations represented in matrix form.

In [268]:
A = np.array([[1,1], [2,1]])
B = np.array([5,8])

solution = np.linalg.solve(A,B)
print(solution)

[3. 2.]


Eigenvalues and eigenvectors can be computed using `np.linalg.eig()`. Eigenvalues are scalars that represent the scaling factor of a linear transformation, while eigenvectors are non-zero vectors that remain in the same direction after the transformation.

In [269]:
A = np.array([[4, 2, 3],
              [1, 3, 3],
              [2, 6, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [ 8.10230638  2.43353975 -2.53584613]
Eigenvectors:
 [[-0.65858851 -0.90421728 -0.26885122]
 [-0.47313086  0.35729958 -0.42092301]
 [-0.5851567   0.23394042  0.86633875]]


## 2. SciPy

SciPy (Scientific Python) is an open-source Python library used for scientific computing and technical computing. It builds on NumPy and provides many user-friendly and efficient numerical routines, such as numerical integration, optimization, statistics, signal processing, and more.

### Sparse Matrix

Sparse matrices are matrices that contain a large number of zero elements. SciPy provides the `scipy.sparse` module, which includes various sparse matrix formats such as Compressed Sparse Row (CSR), Compressed Sparse Column (CSC), and more. These formats allow for efficient storage and computation with sparse data.

The opposite of a sparse matrix is a dense matrix, which contains mostly non-zero elements. Dense matrices are typically represented using NumPy arrays.

In [270]:
import numpy as np

dense = np.array([[0, 1, 0],
                  [0, 0, 2],
                  [3, 0, 4]])

print("Dense Matrix:\n", dense)

Dense Matrix:
 [[0 1 0]
 [0 0 2]
 [3 0 4]]


In [271]:
from scipy.sparse import coo_matrix
# Others are csr_matrix and csc_matrix

sparse = coo_matrix(dense)
print(sparse)

<COOrdinate sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	1
  (1, 2)	2
  (2, 0)	3
  (2, 2)	4


In [272]:
print(sparse.count_nonzero())

print(sparse.getnnz())
print(sparse.getnnz(axis=0))   # columns
print(sparse.getnnz(axis=1))   # rows

print(sparse.shape)
print(sparse.data.shape)

4
4
[1 1 2]
[1 1 2]
(3, 3)
(4,)


In [273]:
dense_again = sparse.toarray()
print("Dense Matrix (revised):\n", dense_again)

Dense Matrix (revised):
 [[0 1 0]
 [0 0 2]
 [3 0 4]]


### Statistical Operations

SciPy provides a wide range of statistical functions and methods for analyzing data.

In [274]:
import scipy.stats as stats

data = [1, 2, 2, 3, 4, 5, 6, 8]

result = stats.describe(data)
print(result)

DescribeResult(nobs=np.int64(8), minmax=(np.int64(1), np.int64(8)), mean=np.float64(3.875), variance=np.float64(5.553571428571428), skewness=np.float64(0.5087022045579557), kurtosis=np.float64(-0.855305466237942))


In [275]:
print(stats.mode(data))

ModeResult(mode=np.int64(2), count=np.int64(2))


In [276]:
print(stats.tmean(data))
print(stats.tvar(data))
print(stats.tstd(data))
print(stats.tmin(data))
print(stats.tmax(data))

3.875
5.553571428571428
2.3566016694748027
1
8


In [277]:
print(stats.skew(data))

0.5087022045579557


In [278]:
print(stats.kurtosis(data))

-0.855305466237942


### Probability Distributions

SciPy includes a comprehensive set of probability distributions, both continuous and discrete. You can use these distributions to model random variables and perform statistical analysis.

In [279]:
from scipy.stats import bernoulli

dist = bernoulli(0.7)

# Probability of success
print(dist.pmf(1))

# Probability of failure
print(dist.pmf(0))

0.7
0.30000000000000004


In [280]:
from scipy.stats import binom

dist = binom(10, 0.5)

# Probability of exactly 6 heads
print(dist.pmf(6))

0.2050781249999999


In [281]:
from scipy.stats import poisson

dist = poisson(mu=5)

# Probability of exactly 3 events
print(dist.pmf(3))

0.1403738958142805


In [282]:
from scipy.stats import norm

dist = norm(loc=0, scale=1)

# Probability density at x = 1
print(dist.pdf(1))

0.24197072451914337


### Numerical Methods

SciPy includes a comprehensive set of numerical methods for solving mathematical problems, including regression, optimization, root finding, interpolation, and numerical integration. These methods are essential for solving complex mathematical problems in various scientific and engineering applications.

In [283]:
import scipy.stats as stats

data = [10, 15, 20, 25, 30]

z_scores = stats.zscore(data)
print(z_scores)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [284]:
from scipy import stats

x = [1, 2, 3, 4, 5]
y = [3, 5, 7, 9, 11]

result = stats.linregress(x, y)

print("Slope:", result.slope)
print("Intercept:", result.intercept)

Slope: 2.0
Intercept: 1.0


In [285]:
from scipy.stats import norm

samples = norm.rvs(loc=0, scale=1, size=5)
print(samples)

[ 0.06313282  0.07277509  0.13088969 -1.49686918  0.74574095]


In [286]:
from scipy.differentiate import derivative

f = lambda x: x**2
print(derivative(f, 3))

     success: True
      status: 0
          df: 5.999999999999972
       error: 2.842170943040401e-14
         nit: 2
        nfev: 11
           x: 3.0


In [287]:
from scipy.integrate import quad

f = lambda x: x**2

result, error = quad(f, 0, 2)
print(result)

2.666666666666667


In [288]:
import numpy as np
from scipy.integrate import trapezoid

x = np.array([0,1,2,3])
y = np.array([0,1,4,9])

area = trapezoid(y, x)
print(area)

9.5


In [289]:
from scipy.integrate import solve_ivp

def f(t, y):
    return y

result = solve_ivp(f, [0, 2], [1])
print(result.y)

[[1.         1.10519301 2.9040598  7.38932547]]


In [290]:
from scipy.optimize import minimize_scalar

f = lambda x: x**2 + 4

result = minimize_scalar(f)

print(result.x)
print(result.fun)

1.147310308261937e-08
4.0


### Working with Graphs

SciPy also provides tools for working with graphs and networks. You can use the `scipy.sparse.csgraph` module to perform graph algorithms such as shortest path, connected components, and minimum spanning tree.

In [291]:
from scipy.sparse.csgraph import csgraph_from_dense

In [292]:
# Undirected Graph
undirected_graph = np.array([[0, 1, 1, 0],
                             [1, 0, 1, 1],
                             [1, 1, 0, 1],
                             [0, 1, 1, 0]])
# Directed Graph
directed_graph = np.array([[0, 1, 1, 0],
                           [0, 0, 1, 1],
                           [0, 0, 0, 1],
                           [0, 0, 0, 1]])

# Represent the graphs as sparse matrices
undirected_sparse = csgraph_from_dense(undirected_graph)
directed_sparse = csgraph_from_dense(directed_graph)

In [293]:
# Unweighted Graphs
unweighted_graph = np.array([[0, 1, 1, 0],
                            [0, 1, 1, 1],
                             [1, 0, 0, 0],
                              [0, 1, 0, 0]])

# Represent the graph as sparse matrices
unweighted_sparse = csgraph_from_dense(unweighted_graph)

In [294]:
# Weighted Graph
weighted_graph = np.array([[0, 4, 3, 0],
                        [0, 5, 6, 2],
                        [3, 0, 0, 0],
                        [0, 4, 0, 0]])

# Represent the graph as sparse matrices
weighted_sparse = csgraph_from_dense(weighted_graph)

In [295]:
# Connected Components
from scipy.sparse.csgraph import connected_components

connected_graph = np.array([[0, 0, 1, 0, 0],
                            [0, 0, 0, 1, 1],
                             [1, 0, 0, 0, 0],
                              [0, 0, 0, 0, 0],
                               [0, 0, 0, 0, 0]])

# Convert to sparse matrix
sparse_matrix = coo_matrix(connected_graph)

# Weakly connected components
weak_components, labels = connected_components(csgraph=sparse_matrix,
                                               directed=True, connection='weak')
print("Num of Weak Components:", weak_components)
print("Labels:", labels)

# Strongly connected components
strong_components, labels = connected_components(csgraph=sparse_matrix,
                                                  directed=True, connection='strong')
print("Num of Strong Components:", strong_components)
print("Labels:", labels)

Num of Weak Components: 2
Labels: [0 1 0 1 1]
Num of Strong Components: 4
Labels: [0 3 0 2 1]


In [296]:
from scipy.sparse.csgraph import shortest_path
from scipy.sparse import csr_matrix

graph = np.array([[0, 4, 5, 0, 0, 0],
                  [4, 0, 11, 9, 7, 0],
                   [5, 11, 0, 0, 3, 0],
                    [0, 9, 0, 0, 13, 2],
                     [0, 7, 3, 13, 0, 6],
                      [0, 0, 0, 2, 6, 0]])

# Convert to sparse matrix
sparse_matrix = csr_matrix(graph)

# Finding shortest path
dist_matrix, predecessors = shortest_path(csgraph=sparse_matrix,
                                          directed=False,
                                          return_predecessors=True)
print("Distance Matrix:\n", dist_matrix)
print("Predecessor Matrix:\n", predecessors)

Distance Matrix:
 [[ 0.  4.  5. 13.  8. 14.]
 [ 4.  0.  9.  9.  7. 11.]
 [ 5.  9.  0. 11.  3.  9.]
 [13.  9. 11.  0.  8.  2.]
 [ 8.  7.  3.  8.  0.  6.]
 [14. 11.  9.  2.  6.  0.]]
Predecessor Matrix:
 [[-9999     0     0     1     2     4]
 [    1 -9999     0     1     1     3]
 [    2     0 -9999     5     2     4]
 [    1     3     4 -9999     5     3]
 [    2     4     4     5 -9999     4]
 [    2     3     4     5     5 -9999]]


In [297]:
# Depth-First Search
from scipy.sparse.csgraph import depth_first_order, depth_first_tree
from scipy.sparse import csr_matrix

graph = np.array([[0, 1, 1, 1, 0],
                  [1, 0, 1, 0, 0],
                   [1, 1, 0, 0, 1],
                    [1, 0, 0, 0, 0],
                     [0, 0, 1, 0, 0]])

# Convert to sparse matrix
sparse_matrix = csr_matrix(graph)

dfs_order = depth_first_order(csgraph=sparse_matrix, i_start=0,
                              directed=False)

print("DFS Order:", dfs_order[0])

dfs_tree = depth_first_tree(csgraph=sparse_matrix, i_start=0,
                            directed=False)

print("DFS Tree:\n", dfs_tree.toarray())

DFS Order: [0 1 2 4 3]
DFS Tree:
 [[0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [298]:
# Breadth-First Search
from scipy.sparse.csgraph import breadth_first_order, breadth_first_tree
from scipy.sparse import csr_matrix

bfs_order = breadth_first_order(csgraph=sparse_matrix, i_start=0,
                               directed=False)

print("BFS Order:", bfs_order[0])

bfs_tree = breadth_first_tree(csgraph=sparse_matrix, i_start=0,
                              directed=False)

print("BFS Tree:\n", bfs_tree.toarray())

BFS Order: [0 1 2 3 4]
BFS Tree:
 [[0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 3. SymPy

SymPy (Symbolic Python) is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible to be understandable and easily extensible. SymPy can perform symbolic differentiation, integration, simplification, and equation solving.

In [299]:
import sympy as sp

sp.sqrt(2)

sqrt(2)

In [300]:
import sympy as sp

x = sp.Symbol('x')
f = x**3 + 2*x**2 + x

# Differentiate
sp.diff(f, x)

3*x**2 + 4*x + 1

In [301]:
sp.diff(f, x, 2)

2*(3*x + 2)

In [302]:
sp.diff(f, x, 3)

6

In [303]:
f = x**2
sp.integrate(f, x)

x**3/3

In [304]:
# Definite Integrals
sp.integrate(x**2, (x, 0, 2))

8/3

In [305]:
x, y = sp.symbols('x y')
f = x**2 * y + y**2

# Partial derivative with respect to x
sp.diff(f, x)

2*x*y

In [306]:
# Partial derivative with respect to y
sp.diff(f, y)

x**2 + 2*y

In [307]:
import sympy as sp

x = sp.Symbol('x')

expr = sp.sin(x)/x
print(sp.limit(expr, x, 0))

# Infinite Limits
print(sp.limit(1/x, x, sp.oo))

1
0


In [308]:
x = sp.Symbol('x')
f = x**3 + 2*x**2 + x

sp.exp(x).series(x, 0, 6)

1 + x + x**2/2 + x**3/6 + x**4/24 + x**5/120 + O(x**6)

In [309]:
sp.exp(x).series(x, 1, 5)

E + E*(x - 1) + E*(x - 1)**2/2 + E*(x - 1)**3/6 + E*(x - 1)**4/24 + O((x - 1)**5, (x, 1))

In [310]:
x = sp.Symbol('x')

eq = x**2 - 5*x + 6
sp.solve(eq, x)

[2, 3]

In [311]:
x, y = sp.symbols('x y')

solutions = sp.solve((x + y - 5,
                      2*x + y - 8),
                       (x, y))

solutions

{x: 3, y: 2}